var PROMPTS={diagnosis:{system:"你是资深初中生物教学专家。分析学生常见理解错误。\n要求：\n1.每个错误:表现→原因→建议\n2.最后5道诊断选择题附答案\n3.适配七年级",user:"分析以下知识点常见错误：\n{topics}\n\n{extra}\n\n先列每个知识点典型错误(表现/原因/建议)，最后给5道诊断题。"},practice:{system:"你是初中生物教师。生成分层练习。\nA层(基础)选择+判断4题\nB层(提升)分析+推理3题\nC层(拓展)探究2题\n每题附答案+解析",user:"针对薄弱点生成三层练习（所有题目答案统一放在最后）：\n{topics}\n\n学情:{extra}（⚠️答案统一放在所有题目最后）\n\n输出A层/B层/C层，附答案。"},concept:{system:"你是初中生物教学专家。请根据以下知识点自动确定最佳对比维度并生成对比辨析材料。\n要求：\n1. 首先判断知识点间的对比关系（如概念对比、过程对比、实验对比等）\n2. 生成合适的多维度对比表\n3. 指出最易混淆的3个点+辨析策略\n4. 语言通俗，教师课堂用语",user:"请对以下知识点进行对比辨析：\n{topics}\n\n补充说明：{extra}\n\n请自动确定对比维度，输出对比表和易混淆点辨析。"},lecture:{system:"你是初中生物教师。提供讲评策略。\n每个错误:话术+演示+互动问题",user:"学生错误:{topics}\n{extra}\n\n给讲评话术、演示建议、互动问题。"}};
var TOPIC_PROMPT={system:"你是课程专家。列出课时核心知识点。\n每行一个,6-10个\n覆盖概念/实验/应用\n只输出知识点名称",user:"课时:{lesson}\n学科:{subject}\n教材:{version}\n\n列出核心知识点,每行一个。"};
var currentScene="diagnosis",selectedTopics=["暗处理目的","遮光对照设计"],currentModels=[];
var IS_FILE=window.location.protocol==="file:";
if(IS_FILE){document.querySelector(".header").insertAdjacentHTML("afterend",'<div style="background:#FFF3E0;color:#E65100;padding:10px 16px;text-align:center;font-size:0.85em;margin-bottom:10px;border-radius:8px;">⚠️ 检测到以 file:// 方式打开，API请求可能被浏览器CORS策略阻止！<br>👉 请双击 <b>启动服务器.bat</b> 或在终端执行 <b>python -m http.server 8765</b> 后访问 http://localhost:8765</div>')}
document.querySelectorAll("#tagRow .tag").forEach(function(t){t.addEventListener("click",function(){this.classList.toggle("selected");updateTopics()})});
function selectScene(e){document.querySelectorAll(".scene-item").forEach(function(x){x.classList.remove("active")});e.classList.add("active");currentScene=e.dataset.scene}
function updateTopics(){selectedTopics=[];document.querySelectorAll("#tagRow .tag.selected").forEach(function(t){selectedTopics.push(t.dataset.topic)})}
function updateModel(){var s=document.getElementById('modelName');if(!currentModels.length)return;var p=currentScene==="diagnosis"||currentScene==="concept"?"reasoner":"chat",m=currentModels[0];currentModels.forEach(function(x){if(x.toLowerCase().indexOf(p)>=0)m=x});s.value=m}
function onProvChange(){var p=document.getElementById('apiProvider').value;document.getElementById('customUrlRow').style.display=p==="custom"?"flex":"none";document.getElementById('modelName').innerHTML='<option value="">请先拉取模型列表</option>';document.getElementById('connStatus').textContent="";currentModels=[]}
function enc(t){try{return btoa(unescape(encodeURIComponent(t)))}catch(e){return btoa(t)}}
function dec(t){try{return decodeURIComponent(escape(atob(t)))}catch(e){return atob(t)}}
function saveCfg(){var k=document.getElementById('apiKey').value.trim();if(!k){alert("请先输入API Key！");return};localStorage.setItem("ps_cfg_v3",JSON.stringify({k:enc(k),p:document.getElementById('apiProvider').value,m:document.getElementById('modelName').value,chat:document.getElementById('customChatUrl').value,models:document.getElementById('customModelsUrl').value}));alert("✅ 已加密保存！\n\n🔐 仅存本地浏览器，不上传。")}
function loadCfg(){try{var r=localStorage.getItem("ps_cfg_v3");if(!r)return;var c=JSON.parse(r);if(c.k)document.getElementById('apiKey').value=dec(c.k);if(c.p){document.getElementById('apiProvider').value=c.p;onProvChange()}if(c.m)document.getElementById('modelName').value=c.m;if(c.chat)document.getElementById('customChatUrl').value=c.chat;if(c.models)document.getElementById('customModelsUrl').value=c.models}catch(e){}}
function chatUrl(){var p=document.getElementById('apiProvider').value;if(p==="custom")return document.getElementById('customChatUrl').value.trim()||"https://api.deepseek.com/v1/chat/completions";if(p==="siliconflow")return"https://api.siliconflow.cn/v1/chat/completions";return"https://api.deepseek.com/v1/chat/completions"}
function modelsUrl(){var p=document.getElementById('apiProvider').value;if(p==="siliconflow")return"";if(p==="deepseek")return"https://api.deepseek.com/models";return document.getElementById('customModelsUrl').value.trim()||""}
function defModels(){var p=document.getElementById('apiProvider').value;if(p==="siliconflow")return["deepseek-ai/DeepSeek-V3","deepseek-ai/DeepSeek-R1","Qwen/Qwen3-235B-A22B","Qwen/Qwen2.5-72B-Instruct","Qwen/Qwen2.5-32B-Instruct","Qwen/Qwen2.5-7B-Instruct","Pro/Llama-4-Maverick-17B-128E-Instruct","THUDM/GLM-4-9B-Chat","01-ai/Yi-1.5-34B-Chat","deepseek-ai/DeepSeek-V2.5","Pro/Llama-3.1-405B-Instruct"];return["deepseek-chat","deepseek-reasoner","deepseek-ai/DeepSeek-V3","deepseek-ai/DeepSeek-R1"]}
function fillMods(arr){currentModels=arr;var s=document.getElementById('modelName');s.innerHTML="";arr.forEach(function(m){var o=document.createElement("option");o.value=m;o.textContent=m;s.appendChild(o)});updateModel()}
function fetchTO(s,u,ms){ms=ms||60000;var ctrl=new AbortController();var t=setTimeout(function(){ctrl.abort()},ms);var opts={method:(u&&u.method)||"GET",headers:new Headers(u&&u.headers||{}),signal:ctrl.signal};if(u&&u.body)opts.body=u.body;return fetch(s,opts).finally(function(){clearTimeout(t)})}
async function apiCall(s,u){var k=document.getElementById('apiKey').value.trim();if(!k){alert("请先输入API Key！");return null};var m=document.getElementById('modelName').value;if(!m||m===""){alert("请先选择模型！");return null};try{var r=await fetchTO(chatUrl(),{method:"POST",headers:new Headers({"Content-Type":"application/json","Authorization":"Bearer "+k}),body:JSON.stringify({model:m,messages:[{role:"system",content:s},{role:"user",content:u}],temperature:0.7,max_tokens:2048})});if(!r.ok){var e=await r.json().catch(function(){return{}});throw new Error(e.error?e.error.message:"HTTP "+r.status)};var d=await r.json();return d.choices[0].message.content}catch(e){if(e.name==="AbortError")throw new Error("请求超时(60s)\n可能原因:CORS阻止(请用启动服务器.bat打开)\n或API地址不可达");if(e.message&&e.message.indexOf("Failed to fetch")>=0)throw new Error("网络请求失败\n请检查: 1.是否用file://打开?(用启动服务器.bat)\n2.网络连接 3.API地址");throw e}}
async function fetchModels(){var k=document.getElementById('apiKey').value.trim();if(!k){alert("请先输入API Key！");return};var st=document.getElementById('connStatus');st.textContent="拉取中...";st.className="status-tag";var mu=modelsUrl();if(!mu){fillMods(defModels());st.textContent="✅ "+currentModels.length+"个模型(预设)";st.className="status-tag status-ok";return};try{var r=await fetchTO(mu,{headers:new Headers({"Authorization":"Bearer "+k})},10000);if(!r.ok){if(r.status===404){fillMods(defModels());st.textContent="✅ "+currentModels.length+"个模型(预设,端点不支持)";st.className="status-tag status-ok";return};throw new Error("HTTP "+r.status)};var d=await r.json();var arr=d.data.map(function(m){return m.id}).filter(function(id){return id.indexOf("embed")<0&&id.indexOf("rerank")<0});if(!arr.length){fillMods(defModels());st.textContent="✅ "+currentModels.length+"个模型(预设)";st.className="status-tag status-ok";return};fillMods(arr);st.textContent="✅ "+arr.length+"个模型";st.className="status-tag status-ok"}catch(e){fillMods(defModels());var msg=e.name==="AbortError"?"超时,使用预设":e.message.substring(0,25);st.textContent="⚠️ "+msg+" → "+currentModels.length+"个预设模型";st.className="status-tag status-ok"}}
async function testConn(){var k=document.getElementById('apiKey').value.trim();if(!k){alert("请先输入API Key！");return};var m=document.getElementById('modelName').value;if(!m||m===""){alert("请先拉取模型列表并选择模型！");return};var st=document.getElementById('connStatus');var url=chatUrl();st.textContent="测试中("+url.substring(8,35)+"...)";st.className="status-tag";st.title="请求地址: "+url+"\n模型: "+m;try{var r=await fetch(url,{method:"POST",headers:new Headers({"Content-Type":"application/json","Authorization":"Bearer "+k}),body:JSON.stringify({model:m,messages:[{role:"system",content:"你是一个助手"},{role:"user",content:"请回复连接成功"}],temperature:0.7,max_tokens:100})});if(!r.ok){var e=await r.json().catch(function(){return{}});throw new Error("HTTP "+r.status+": "+(e.error?e.error.message:r.statusText))};var d=await r.json();st.textContent="✅ 连接成功 ("+url.substring(8,30)+")";st.className="status-tag status-ok"}catch(e){var msg;if(e.name==="TypeError"&&e.message.indexOf("Failed")>=0)msg="网络不通: "+url.substring(0,50);else if(e.name==="AbortError")msg="超时(60s): "+url.substring(0,40);else if(e.message.indexOf("401")>=0)msg="API Key无效(401)";else if(e.message.indexOf("403")>=0)msg="无权访问(403)";else msg=e.message.substring(0,50);st.textContent=msg;st.className="status-tag status-err";st.title="完整错误: "+e.message+"\n请求URL: "+url}}
async function fetchTopics(){var ln=document.getElementById('lessonName').value.trim();if(!ln){alert("请输入课时名称！");return};var st=document.getElementById('topicStatus');st.textContent="⏳ AI生成中...";st.style.color="#888";try{var sb=document.getElementById('subject').value.trim(),vr=document.getElementById('textbookVer').value.trim();var um=TOPIC_PROMPT.user.replace("{lesson}",ln).replace("{subject}",sb).replace("{version}",vr);var rt=await apiCall(TOPIC_PROMPT.system,um);if(!rt){st.textContent="未获取到结果";return};var topics=[],lines=rt.split("\n");lines.forEach(function(l){var t=l.trim();if(!t||t.startsWith("#")||t.startsWith("```")||t.indexOf("以下是")>=0||(t.indexOf("知识点")>=0&&t.length>20))return;t=t.replace(/^\d+[\.\)、]\s*/,"").replace(/^[-*•·]\s*/,"").trim();if(t.length>1&&t.length<40)topics.push(t)});if(!topics.length){st.textContent="未解析到知识点";st.style.color="#E65100";return};var tr=document.getElementById('tagRow');tr.innerHTML="";topics.forEach(function(t){var sp=document.createElement("span");sp.className="tag selected ai-generated";sp.dataset.topic=t;sp.textContent=t;sp.addEventListener("click",function(){this.classList.toggle("selected");updateTopics()});tr.appendChild(sp)});updateTopics();st.textContent="✅ 生成了 "+topics.length+" 个知识点";st.style.color="#2E7D32"}catch(e){st.textContent=e.message.substring(0,50);st.style.color="#C62828"}}
function fmtOut(t){if(!t)return"";var h=t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
h=h.replace(/```([^`]+)```/g,"<pre>$1</pre>");
h=h.replace(/`([^`]+)`/g,"<code>$1</code>");
h=h.replace(/^[ ]*#{1,3}[ ]+(.+)$/gm,function(m,x){
  var n=m.match(/^[ ]*#+/)[0].replace(/ /g,"").length;
  return n===1?"<h2>"+x+"</h2>":n===2?"<h2>"+x+"</h2>":"<h3>"+x+"</h3>";
});
h=h.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");
h=h.replace(/^[ ]*[-*][ ]+(.+)$/gm,"<li>$1</li>");
h=h.replace(/((?:<li>.*?<\/li>\s*)+)/g,"<ul>$1</ul>");
h=h.replace(/^[ ]*&gt;[ ]?(.+)$/gm,"<blockquote>$1</blockquote>");
h=h.replace(/\n\n+/g,"<br><br>");
h=h.replace(/\n/g,"<br>");
return h}
async function generate(){updateTopics();if(!selectedTopics.length){alert("请至少选择一个知识点！");return};var b=document.getElementById('btnGenerate'),o=document.getElementById('outputBox'),u=document.getElementById('userInput').value.trim();b.disabled=true;b.textContent="生成中...";o.innerHTML='<div class="loading">正在调用AI模型...</div>';var p=PROMPTS[currentScene],ts=selectedTopics.map(function(t){return"• "+t}).join("\n"),ex=u||"南岳庙九年义务制学校192班，38人。第三单元（光合作用）均分49.2，及格率仅36%，23人不及格。暗处理正确率约40%，酒精脱色原理约31%，遮光对照约48%。",um=p.user.replace("{topics}",ts).replace("{extra}",ex);document.getElementById('promptPreview').style.display="block";document.getElementById('promptText').textContent=um;try{var r=await apiCall(p.system,um);if(r){o.innerHTML=fmtOut(r)}else{o.innerHTML='<div class="error">未获取到结果</div>'}}catch(e){o.innerHTML='<div class="error">'+e.message.replace(/\n/g,"<br>")+'<br><br>提示: CORS/网络错误请双击启动.bat打开</div>'}finally{b.disabled=false;b.textContent="调用AI生成"}}
function copyOut(){var t=document.getElementById('outputBox').innerText;if(!t.trim()||t.indexOf("👈")>=0){alert("暂无内容可复制");return};navigator.clipboard.writeText(t).then(function(){alert("✅ 已复制！")})}
window.addEventListener("load",function(){loadCfg();updateTopics()});
